'use client';
import Image from 'next/image';
import { useState } from 'react';
import { ChevronDown, RotateCcw, Search, ShieldCheck } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Heading, Reading, Refs } from './common';
import { glossary, modules, sources } from '@/lib/guide-data';
import { acceptance, hardwareGates, questions, requirements, researchPlan, stack } from '@/lib/guide-extra';
import { fieldRange, fields } from '@/lib/lab';

export function Architecture() {
  const stages = [
    ['01 / PHYSICAL','SFP+ + GTH + PCS/MAC','Recover the link, frame boundaries and error status. Board-specific IP and clocks.'],
    ['02 / TENTATIVE','Ethernet / IPv4 / UDP + payload','Filter the declared subset. Check length and checksums. No committed quote or order yet.'],
    ['03 / COMMIT','Frame validation barrier','Publish only when the complete frame passes every integrity and framing check.'],
    ['04 / STATE','Sequence health + quote table','Enforce epoch, freshness and capacity. Resolve consecutive same-symbol updates.'],
    ['05 / ADMISSION','Decision + risk + reservation','Check health, age and limits. Reserve exposure and an output slot atomically.'],
    ['06 / TRANSMIT','OrderIntent-v1 + TX scheduler','Serialize a complete response without MAC underflow. Sent bytes cannot be recalled.'],
  ];
  const cycles = [['rst_n=0','Clear fields and both result flags. Ignore packet_valid.'],['Idle cycle','Hold fields; decoded_valid=0, decode_error=0.'],['Accepted quote','Latch fields; decoded_valid=1, decode_error=0.'],['Rejected quote','Hold fields; decoded_valid=0, decode_error=1.'],['Next quote on next edge','Latch new fields. Valid may stay high.']];
  return <><Heading eyebrow="DESIGN BEFORE OPTIMIZATION" title="Separate tentative work from irreversible effects"><p>The application runs in the FPGA. C++ supplies traffic, a simulated venue and control; Python supplies independent models and tests. Reuse a supported MAC/PCS baseline, then own the application pipeline.</p></Heading>
    <div className="architecture-flow">{stages.map(([step,title,copy],i)=><div className={`flow-stage ${i===2?'commit-stage':''}`} key={step}><span className="eyebrow">{step}</span><h3>{title}</h3><p>{copy}</p></div>)}</div>
    <p className="feedback-line"><RotateCcw size={19}/><span><strong>Feedback:</strong> the C++ simulated venue returns acknowledgements, rejects and fills over the same full-duplex link. Validated feedback updates the order tracker; unknown outcomes disarm admission.</span></p><p>Control: onboard processor, C++ register I/O, AXI-Lite configuration epochs, counters, arm and kill. Observability: tagged timestamps, bounded traces and ILA. Neither path may silently corrupt or stall the data path.</p><Refs ids={['pg210','axis','uio','cdc']}/>
    <section className="band"><Heading eyebrow="YOUR FIRST REAL RTL BLOCK" title="market_data_decoder.sv"/><p>This first unit sees an assembled 248-bit payload. It cannot inspect Ethernet, packet length, FCS or UDP checksums. Later stages provide those guarantees.</p><div className="two-col"><div><h3>Registered contract</h3><p>{modules[0].contract}</p><p>Use <code>logic</code>, one <code>always_ff @(posedge clk)</code> block and nonblocking <code>&lt;=</code> assignments. Synchronous active-low reset is the proposed convention; low polarity does not imply asynchronous reset.</p><p><strong>Proposed quote policy:</strong> type=1, bid no greater than ask, both sizes nonzero. The zero-size rule belongs to this custom snapshot format, not every exchange.</p></div><div><h3>At the edge, then after it settles</h3><Table><TableHeader><TableRow><TableHead>Input</TableHead><TableHead>Registered result</TableHead></TableRow></TableHeader><TableBody>{cycles.map(([a,b])=><TableRow key={a}><TableCell>{a}</TableCell><TableCell>{b}</TableCell></TableRow>)}</TableBody></Table><p className="small muted">A downstream register samples the new fields at the following edge. In cocotb, observe after RisingEdge + ReadOnly.</p></div></div>
      <h3>Payload-v1 field map</h3><Table><TableHeader><TableRow>{['Field','Bits','packet_in slice','Wire bytes','Example'].map(s=><TableHead key={s}>{s}</TableHead>)}</TableRow></TableHeader><TableBody>{fields.map((f,i)=>{const r=fieldRange(i);return <TableRow key={f.name}><TableCell><code>{f.name}</code></TableCell><TableCell>{f.bits}</TableCell><TableCell><code>[{r.high}:{r.low}]</code></TableCell><TableCell>{r.byte}-{r.byte+r.length-1}</TableCell><TableCell><code>{f.initial}</code></TableCell></TableRow>;})}</TableBody></Table><p className="small">Unsigned fields; big-endian field bytes; price scale 10,000, not binary Q format. Define timestamp units before using the field beyond an opaque test value.</p><Refs ids={['timingmodel','itch']}/>
    </section><section className="band"><Heading eyebrow="BOUND THE DESIGN" title="Initial operating profile"/><ul className="columns-list">{['64 configured symbol slots, with explicit mapping before indexing.','One global 32-bit quote sequence and explicit session/recovery protocol.','Untagged Ethernet, IPv4 without options or fragments, configured UDP ports.','One 31-byte synthetic quote per datagram; no claimed ITCH compatibility.','Static lab addresses and neighbor configuration. ARP, DHCP, IPv6 and routing are not assumed.','Finite frame, descriptor and outstanding-order queues. Choose depths from a traffic budget, then sweep them.','Isolated trusted lab peer. Address filtering is not authentication.','Disarmed after boot, link failure, stale control heartbeat, sequence gap or unresolved order outcome.'].map(x=><li key={x}>{x}</li>)}</ul><p className="small">Proposed engineering choices, not exchange requirements. Freeze them in a versioned specification.</p></section>
    <section className="band"><Heading eyebrow="VOCABULARY IN CONTEXT" title="Terms you will actually use"/><div className="glossary">{glossary.map(([term,meaning])=><details key={term}><summary>{term}<ChevronDown size={15}/></summary><p>{meaning}</p></details>)}</div></section></>;
}
export function Verification() {
  const [query,setQuery]=useState('');
  const matches=modules.filter(m=>JSON.stringify(m).toLowerCase().includes(query.toLowerCase()));
  return <><Heading eyebrow="REQUIREMENTS -> TESTS -> EVIDENCE" title="Make failure behavior part of the design"><p>{requirements.length} requirements and {modules.reduce((n,m)=>n+m.cases.length,0)} planned edge-case entries. A test specification, not an executed regression or exhaustive proof.</p></Heading>
    <Table><TableHeader><TableRow>{['ID','Requirement','Acceptance intent','Owners'].map(s=><TableHead key={s}>{s}</TableHead>)}</TableRow></TableHeader><TableBody>{requirements.map(([id,name,statement,owners])=><TableRow key={id}><TableCell><code>{id}</code></TableCell><TableCell>{name}</TableCell><TableCell>{statement}</TableCell><TableCell><code>{owners}</code></TableCell></TableRow>)}</TableBody></Table>
    <section className="band"><div className="search-heading"><Heading eyebrow="RTL + SOFTWARE CONTRACTS" title="Every work package has a test boundary"/><div className="search-field"><Search size={17}/><Input aria-label="Search module contracts and edge cases" placeholder="Search CDC, overflow, Python..." value={query} onChange={e=>setQuery(e.target.value)}/></div></div><p className="small muted">{matches.length} of {modules.length} work packages</p><div className="module-list">{matches.map(m=><details key={m.id}><summary><span className="module-id">{m.id}</span><span className="module-title"><code>{m.name}</code><small>{m.language} / weeks {m.phase}</small></span><ChevronDown size={17}/></summary><div className="module-content"><h3>{m.role}</h3><p><strong>Contract.</strong> {m.contract}</p><h4>Required edge-case tests</h4><ul className="columns-list">{m.cases.map(c=><li key={c}>{c}</li>)}</ul><p className="gate"><ShieldCheck size={18}/><span><strong>Evidence.</strong> {m.evidence}</span></p><Refs ids={m.refs}/></div></details>)}</div>{matches.length===0&&<output>No matching work package. Clear or broaden the search.</output>}</section>
    <section className="band"><Heading eyebrow="REGRESSION EXIT CRITERIA" title="A green terminal is not the whole result"/><ol className="numbered-checks">{acceptance.map(a=><li key={a}>{a}</li>)}</ol><Refs ids={['verilator','formal','cdc','benchmark']}/></section><section className="band two-col"><div><h3>The independent-model rule</h3><p>Python describes expected behavior, not a line-for-line copy of the RTL. Compare transaction streams and final state. Preserve an independently calculated golden vector.</p><p>C++ parses bounded buffers, not untrusted packed-struct casts. Test truncation, alignment, endianness and values above 2^53. ASan/UBSan help; unsigned overflow still needs explicit checks.</p><Refs ids={['asan','ubsan']}/></div><div><h3>The failure-evidence bundle</h3><p>Retain requirement ID, smallest input, seed, versions, expected/observed behavior, waveform, root cause, fix and regression test.</p><p>Fail for missing reports, zero discovered tests, skipped required tests, timeouts and stale artifacts. Test scripts with intentionally bad reports and paths containing spaces.</p></div></section></>;
}
export function Readings() {
  const [query,setQuery]=useState('');
  const matches=sources.filter(s=>JSON.stringify(s).toLowerCase().includes(query.toLowerCase()));
  return <><div className="search-heading"><Heading eyebrow="PRIMARY SOURCES, WITH PROJECT NOTES" title="Read the part that unlocks the next step"><p>Highlights are paraphrases unless in quotation marks. Each entry identifies where to look and what to implement. Releases, prices and postings were checked for this edition; recheck before installing or buying.</p></Heading><div className="search-field"><Search size={17}/><Input aria-label="Search annotated sources" placeholder="Search checksum, cocotb, timing..." value={query} onChange={e=>setQuery(e.target.value)}/></div></div><p className="small muted">{matches.length} of {sources.length} sources / Scheduling now; protocols at their milestone.</p><div className="reading-grid">{matches.map(s=><Reading key={s.id} source={s}/>)}</div>{matches.length===0&&<output>No matching source. Clear or broaden the search.</output>}</>;
}
export function Hardware() {
  const board=sources.find(s=>s.id==='kr260')!;
  const tree=['rtl/          Portable core and board wrappers, separated','sim/          cocotb drivers, monitors, scoreboards and runner','formal/       Property harnesses and declared assumptions','uvm/          Optional focused risk-block environment','python/       Codec, reference model and report analysis','host/         C++ replay, venue simulator and register control','constraints/  Board-reviewed pins and clocks','scripts/      Tcl build/reports and Python report checks','docs/         Protocol, interfaces, clock/reset map, requirements','fixtures/     Independent vectors and synthetic captures','evidence/     Summaries; raw runs referenced by manifest'];
  return <><Heading eyebrow="RESOLVE BEFORE BUYING" title="The board is only one part of the link"><p>The KR260 is a candidate, not a locked purchase. Its single 10G SFP+ port fits an endpoint architecture. The four RJ45 ports are 1G, not another 10G path.</p></Heading><div className="hardware-layout"><figure><a href="/kr260-interfaces.jpg" target="_blank" rel="noreferrer"><Image unoptimized src="/kr260-interfaces.jpg" alt="AMD KR260 annotated interfaces with one 10G SFP+ cage and four 1G Ethernet ports" width="1200" height="1200" loading="lazy"/></a><figcaption>Official interface reference. Image: <a href={board.url} target="_blank" rel="noreferrer">AMD</a>.</figcaption></figure><div><div className="hardware-price"><strong>$349</strong><span>AMD-listed MSRP, checked 7 Sep 2026.<br/>Listed lead time: 26 weeks. Not a stock or delivered-cost quote.</span></div><ol className="numbered-checks">{hardwareGates.map(g=><li key={g}>{g}</li>)}</ol><Refs ids={['kr260','kriaip','bist','license','features']}/></div></div>
    <section className="band"><Heading eyebrow="TOOLCHAIN / ADOPT IN STAGES" title="Tools earn their place by what they verify"/><Table><TableHeader><TableRow>{['Tool / language','When','Responsibility','Proof it works'].map(s=><TableHead key={s}>{s}</TableHead>)}</TableRow></TableHeader><TableBody>{stack.map(s=><TableRow key={s.name}><TableCell><strong>{s.name}</strong></TableCell><TableCell>{s.when}</TableCell><TableCell>{s.purpose}</TableCell><TableCell>{s.proof}</TableCell></TableRow>)}</TableBody></Table><Refs ids={['cocotb','versions','verilator','uvm','xsim','tcl','formal']}/></section><section className="band two-col"><div><h3>Freeze a tested environment</h3><p>Use Linux or WSL2 for portable simulation and host software. Pin packages, simulator, compiler and UVM versions after a smoke test. This audit did not execute its candidate pairing on your RTL.</p><p>Log Vivado, device, board revision, IP versions, constraints and licenses. Vendor builds and encrypted models are separate from portable core tests.</p></div><div><h3>Keep ownership clear</h3><p>Document your RTL, generated IP and third-party blocks. Legacy verilog-ethernet and successor Taxi have different licenses; review the chosen revision before distribution.</p><p>Use personal/university-approved systems. Do not include employer HDL, documents, captures, equipment access or debug screenshots without authorization.</p><Refs ids={['ethernet','taxi','license']}/></div></section><section className="band"><Heading eyebrow="PROPOSED REPOSITORY SHAPE" title="One route from source to evidence"/><pre className="repo-tree">{tree.join('\n')}</pre><p className="small">Proposed layout only. This guide did not create or verify these FPGA files.</p></section></>;
}
export function Research() {
  return <><Heading eyebrow="AN EXPERIMENT, NOT A PERFORMANCE PROMISE" title="Measure the cost of waiting for integrity"/><p className="research-question">{researchPlan.question}</p><p><strong>Hypothesis.</strong> {researchPlan.hypothesis}</p><div className="variant-grid">{researchPlan.variants.map((v,i)=><article key={v}><span className="stage-number">{i===0?'A':'B'}</span><h3>{v}</h3></article>)}</div><div className="two-col"><div><h3>Hold these constant</h3><ul>{researchPlan.controls.map(c=><li key={c}>{c}</li>)}</ul></div><div><h3>Measure these outcomes</h3><ul>{researchPlan.measures.map(m=><li key={m}>{m}</li>)}</ul></div></div><p className="status warning">{researchPlan.limitations}</p>
    <section className="band"><Heading eyebrow="RELATED WORK" title="Learn from architectures, not headline numbers"/><div className="reading-grid">{sources.filter(s=>['feedpaper','corundum','parserpaper'].includes(s.id)).map(s=><Reading key={s.id} source={s}/>)}</div></section><section className="band"><Heading eyebrow="MAKE THE DEMO INTERESTING" title="A fault tournament with real evidence"/><p>Use a fixed scenario deck: healthy stream, repeated symbol, malformed final byte, missing sequence, full queue, kill, delayed fill and link restart. Predict counts and final state before each run. Score only when the independent scoreboard agrees.</p><div className="challenge-grid">{[['01','Byte detective','Locate a wrong slice from a waveform, then write the regression.'],['02','Queue under pressure','Find the smallest burst reaching the queue bound. Account for every frame.'],['03','No double release','Inject duplicate feedback and a cancel/fill race. Explain the reservation.'],['04','Timing investigator','Locate the post-route critical path. Try one change and report the tradeoff.']].map(([n,title,copy])=><article key={n}><span className="eyebrow">CHALLENGE {n}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section><section className="band"><Heading eyebrow="EXPLAIN IT WITHOUT AI" title="Answer before revealing the explanation"/><div className="question-list">{questions.map(([q,a])=><details key={q}><summary>{q}<ChevronDown size={16}/></summary><p>{a}</p></details>)}</div><p className="small">Use AI for hints, review and adversarial tests. Write expected behavior first, inspect changes, and reproduce results yourself.</p></section><section className="band two-col"><div><h3>Your final evidence package</h3><ul>{['System and clock/reset diagrams; ownership and IP attribution.','Versioned requirements, protocol and module contracts.','Reproducible regression, coverage and selected formal results.','Post-route reports and reviewed timing exceptions.','Hardware demo, raw traces, measurements and uncertainty.','Experiment report with negative results and limitations.'].map(s=><li key={s}>{s}</li>)}</ul></div><div><h3>Research boundary</h3><p>Standards, exchange specifications, official tool documentation, role descriptions and three papers informed this edition. Informal career/forum advice supplied questions, not authoritative requirements.</p><p>Open gates: pin-level audit, board access, licenses, simulator smoke tests, novelty and actual implementation results. No web review guarantees every edge case or a hiring outcome.</p></div></section></>;
}
